### ISSUE TITLE
backend-url setting gets corrupted somehow

### ISSUE THREAD

**Issue by HebaruSan** [KSP-SpaceDock/OpenDock#4]
### Description (What went wrong?):

OpenDock loads to a large loading animation and stays that way:

![image](https://user-images.githubusercontent.com/1559108/36321507-af7057f4-130f-11e8-8205-06ed6800ad99.png)

If I open the dev tools and delete the div containing that graphic, the page content is there but (unsurprisingly) not initialized:

![image](https://user-images.githubusercontent.com/1559108/36321589-e7256a9a-130f-11e8-96de-9b296ad4aaad.png)

### Reproduction Steps (What did you do?):

Set these in `config.php` across different tests:

```
        'backend-url' => 'http://127.0.0.1:5000/',
```

```
        'backend-url' => 'https://127.0.0.1:5000/',
```

### Expected Behavior (What do you think should have happened instead?):

Presumably the loading screen should only be visible for a few seconds or less.

### Environment (OS/Browser/Plugins/etc):

- Ubuntu
- Chromium

### Extra Information (Screenshots/Error Messages/Javascript Console Output):

Several errors show up in the browser console with invalid URLs that are apparent perversions of the configured `backend-url`. It looks like the first colon is spliced out, and then `http://` is added to the beginning:

With `http://127.0.0.1:5000/`:

![image](https://user-images.githubusercontent.com/1559108/36321426-706a4204-130f-11e8-9ae3-6241babe156f.png)

With `https://127.0.0.1:5000/`:

![image](https://user-images.githubusercontent.com/1559108/36321431-73319cee-130f-11e8-928e-f8d9a7a459c2.png)

Maybe the setting isn't actually supposed to be a URL?

**Comment by Xinayder** [comment]
You don't need the protocol in the `backend-url` config field.

**Comment by HebaruSan** [comment]
Removing the protocol gives me this:

```
        'backend-url' => '127.0.0.1:5000/',
```

![image](https://user-images.githubusercontent.com/1559108/36322982-09978216-1315-11e8-94f7-115956229273.png)

I assume the double slashes are the culprit. I'd suggest renaming this setting to `backend-host` since it does not work with URLs.

**Comment by StollD** [comment]
OpenDock used to prefix the value from `backend-url` with `//` automatically (so it should use the same protocol the site itself used).

I changed it to detect if it is prefixed with http:// or https:// and if thats the case, use the protocol specified by the user, otherwise use the one the site uses.

https://github.com/KSP-SpaceDock/OpenDock/commit/999fdce402ddf1afa3f7d93016ac696ade726449

**Comment by HebaruSan** [comment]
That looks like a fix to me. Thanks!

**Comment by HebaruSan** [comment]
Is it possible to bootstrap from an empty database? My backend seems to be returning nothing for these four calls, and I was expecting that I could start from nothing, register the first user, upload the first mod, etc. However, an exception is thrown because `browse.data` is undefined:

![image](https://user-images.githubusercontent.com/1559108/36328490-f1a39394-1327-11e8-9651-66a4f17b8179.png)

The code where this exception is thrown:

https://github.com/KSP-SpaceDock/OpenDock/blob/77b61b5140d45c561ad90dc81899cf856962f36a/scripts/index.js#L13-L19

I can't tell whether the front end should be more prepared for this possibility, or if the backend should be returning something.

**Comment by Xinayder** [comment]
If I recall correctly, you need to install some plugins, more specifically `adapter`, `search` and `transformers`.

**Comment by StollD** [comment]
The backend has it's own command for that, it can setup the database with the data that is required to use it.

```
usage: sdb setup [-dummy=true|false]

The setup subcommand will add an administrator account, a normal user,
publisher, game, game admin and some dummy mods to the database.

If you set the dummy flag to false, only an admin account will be added.
```

This is mainly used to populate internal data (like the various permissions).

Also, the request fails because you try to browse the mods for a game with the gameshort `KSP`, since your database is empty, the game isn't found and the backend returns a 404 error message. The dummy data that is added by `sdb setup` uses `kerbal-space-program` as the short name (the same that SpaceDock uses).

OpenDock currently requires that one game is added to the database, #2 tries to change that, but I didn't have the time to finish it properly.

**Comment by HebaruSan** [comment]
But that's a _long_ name. :(

Hmm, I did run `sdb setup`, both before and after installing the plugins. Does it run differently with plugins installed?

**Comment by StollD** [comment]
It shouldn't. Maybe it is simply the `KSP` vs. `kerbal-space-program` issue.

**Comment by HebaruSan** [comment]
Similar result with `kerbal-space-program`:

![image](https://user-images.githubusercontent.com/1559108/36329587-1a8957fe-132c-11e8-9b98-f7fd9f5e08d4.png)

**Comment by HebaruSan** [comment]
Trying `http://127.0.0.1:5000/api/users/current` in a browser says:

```json
{"codes":[1035],"error":true,"reasons":["You need to be logged in to access this page"]}
```

... which seems like a reasonable enough response. It's true that I'm not logged in, and it makes sense to hide certain info from anonymous users.

**Comment by StollD** [comment]
OpenDock expects that response and deals with it. However, since the browse stuff is what is failing (and it isn't limited to logged in users), could you post the response of `/api/games` please?

**Comment by HebaruSan** [comment]
That returns the empty string, or as my browser puts it:

> This page isn’t working
> 127.0.0.1 didn’t send any data.
> ERR_EMPTY_RESPONSE

**Comment by StollD** [comment]
Thats really confusing, it should at least return an empty array.

My last idea would be to delete and recreate the database completely, but I am unsure how much that would actually help

**Comment by Xinayder** [comment]
What about your database, is it populated?

**Comment by StollD** [comment]
He said he ran `sdb setup` two times, so I would assume it is.

**Comment by HebaruSan** [comment]
Yeah, if there's some way of independently verifying that `sdb setup` worked, I'll happily try it, but for now I'm assuming it worked.

**Comment by StollD** [comment]
Well, you could open the database and check if there is something inside of the tables. Or you could export it to an .sql file and upload it, so we can check.

**Comment by HebaruSan** [comment]
OK, here's some psql command line. I'll prune the tables that don't seem related...

`SELECT * FROM pg_catalog.pg_tables ORDER BY tableowner;`

```
     schemaname     |        tablename        | tableowner | tablespace | hasindexes | hasrules | hastriggers | rowsecurity 
--------------------+-------------------------+------------+------------+------------+----------+-------------+-------------
 public             | abilities               | spacedock  |            | t          | f        | f           | f
 public             | download_events         | spacedock  |            | t          | f        | f           | f
 public             | follow_events           | spacedock  |            | t          | f        | f           | f
 public             | referral_events         | spacedock  |            | t          | f        | f           | f
 public             | featureds               | spacedock  |            | t          | f        | f           | f
 public             | games                   | spacedock  |            | t          | f        | f           | f
 public             | shared_authors          | spacedock  |            | t          | f        | f           | f
 public             | tokens                  | spacedock  |            | t          | f        | f           | f
 public             | game_versions           | spacedock  |            | t          | f        | f           | f
 public             | mod_followers           | spacedock  |            | t          | f        | f           | f
 public             | role_abilities          | spacedock  |            | t          | f        | f           | f
 public             | mods                    | spacedock  |            | t          | f        | f           | f
 public             | mod_lists               | spacedock  |            | t          | f        | f           | f
 public             | mod_list_items          | spacedock  |            | t          | f        | f           | f
 public             | mod_versions            | spacedock  |            | t          | f        | f           | f
 public             | publishers              | spacedock  |            | t          | f        | f           | f
 public             | ratings                 | spacedock  |            | t          | f        | f           | f
 public             | role_users              | spacedock  |            | t          | f        | f           | f
 public             | roles                   | spacedock  |            | t          | f        | f           | f
 public             | users                   | spacedock  |            | t          | f        | f           | f
```

```
spacedockbackend=> select * from games;
 id |          created_at           |          updated_at           | deleted_at | meta |         name         | active | altname | rating |          releasedate          |        short         | publisher_id | description | short_description 
----+-------------------------------+-------------------------------+------------+------+----------------------+--------+---------+--------+-------------------------------+----------------------+--------------+-------------+-------------------
  2 | 2018-02-15 21:55:44.274209-06 | 2018-02-15 21:55:44.275501-06 |            | {}   | Factorio             | t      |         |      0 | 2018-02-15 21:55:44.274091-06 | factorio             |            2 |             | 
  1 | 2018-02-15 21:55:44.268473-06 | 2018-02-15 21:56:03.887121-06 |            | {}   | Kerbal Space Program | t      |         |      0 | 2018-02-15 21:55:44.268388-06 | kerbal-space-program |            1 |             | 
(2 rows)
```

**Comment by Xinayder** [comment]
Were you running the backend when you queried `/api/games`?

EDIT: if it doesn't work, try adding a trailing slash, e.g. `/api/games/`

**Comment by HebaruSan** [comment]
Yup. If I wasn't, nothing would have been listening on that port, so it would have said "The site can't be reached"/ERR_CONNECTION_REFUSED instead.

![image](https://user-images.githubusercontent.com/1559108/36330684-54b5cbc0-1330-11e8-9570-bd29014569c1.png)

**Comment by Xinayder** [comment]
Can you screenshot the error that is being thrown by `sdb`?

**Comment by HebaruSan** [comment]
sdb isn't raising errors. The terminal in that screenshot shows sdb while the page is refreshed.

**Comment by StollD** [comment]
Thats a go stacktrace, so something is going terribly wrong there. So not really a user error, but an exception thrown by the code.

Normally it shouldn't show those :D

**Comment by HebaruSan** [comment]
Aha! I guess that "redis" thing is required after all, going by the port number?

```
2018/02/16 15:51:40 http: panic serving 127.0.0.1:58344: dial tcp [::1]:6379: getsockopt: connection refused
goroutine 1108 [running]:
```

Sorry, I didn't know what that was. I'll go look it up...

**Comment by StollD** [comment]
Change `store-type: "redis"` to `store-type: "memory"` in your `config.yml`, then it shouldn't try to use redis.

**Comment by HebaruSan** [comment]
That was definitely it!!

```json
{"count":2,"data":[{"active":true,"altname":"","created":"2018-02-15T21:55:44.274209-06:00","description":"","id":2,"meta":{},"name":"Factorio","publisher":2,"rating":0,"releasedate":"2018-02-15T21:55:44.274091-06:00","short":"factorio","short_description":"","updated":"2018-02-15T21:55:44.275501-06:00"},{"active":true,"altname":"","created":"2018-02-15T21:55:44.268473-06:00","description":"","id":1,"meta":{},"name":"Kerbal Space Program","publisher":1,"rating":0,"releasedate":"2018-02-15T21:55:44.268388-06:00","short":"kerbal-space-program","short_description":"","updated":"2018-02-15T21:56:03.887121-06:00"}],"error":false}
```

![image](https://user-images.githubusercontent.com/1559108/36331066-fd0a1e92-1331-11e8-8fbb-dda1f2aa2f18.png)

**Comment by HebaruSan** [comment]
And after installing `redis-server`, using redis seems to work as well.

If it's OK with you, I'd like to use my notes from this to make the README more idiot-proof. I think I hit most of the stumbling blocks that a new person is likely to encounter.

**Comment by StollD** [comment]
I would love that! It's always terribly hard to write a README if you wrote the program too, because you don't know which things might be obvious, and which are hard to spot.
